import { NextIntlClientProvider, hasLocale } from "next-intl";
import type { Metadata } from "next";
import { Geist, } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Footer from "@/components/shared/footer/Footer";
import ReactQueryProvider from "../ReactQueryProvider";
import PageLoader from "@/components/shared/PageLoader";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${geistSans.className} antialiased`}
      >
        <NextIntlClientProvider>
          <ReactQueryProvider>
            <div className="min-h-dvh h-full flex flex-col justify-between">
              <Navbar />
              <div className="flex-1">
                <PageLoader />
                {children}
                <Toaster />
              </div>
              <Footer />
            </div>
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
